export const APP_NAME="SynapseLogix"
export const APP_DESC="SynapseLogix"
export const APP_URL="http://localhost"
export const APP_KEYWORDS="SaaS, Djagno, Machine Learning, AI, Neural Netoworks"
export const GITHUB_URL="https://github.com/sfsultan"
export const TWITTER_URL="https://twitter.com/PyPills"