import "./globals.css";
import type { Metadata, ResolvingMetadata } from 'next'
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "@/components/nav-bar";
import Footer from "@/components/footer";
import Banner from "@/components/banner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Banner />
          <Navbar />
          <div className="mx-auto max-w-screen-xl">
              {children}
          </div>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
