import Image from "next/image";
import * as React from "react";
import Link from "next/link";
import type { Metadata, ResolvingMetadata } from "next";
import { Button } from "@/components/ui/button";
import { allDocs, Doc } from "contentlayer/generated";
import { compareDesc } from "date-fns";

import { MoveRight } from "lucide-react";

export const metadata: Metadata = {
  title: "Homepage",
  description: "Generated by create next app",
};

export default function Home() {
  const posts: Doc[] = allDocs.sort((a, b) => {
    return compareDesc(new Date(a.published), new Date(b.published));
  });
  return (
    <main className="flex flex-row min-h-screen columns-2 gap-8">
      <div className="w-3/4">
        {allDocs.map((doc) => (
          <article key={doc._id} className="border-b pb-10 mb-5 relative">
            <div className="flex flex-row justify-between mb-5">
              <div className="flex flex-wrap">
                {doc.keywords && doc.splitKeywords.map((k:string) => (
                  <a key={k}
                  className="bg-blue-100 text-blue-800 text-sm font-medium mr-2 px-2.5 py-0.5 rounded dark:bg-blue-200 hover:bg-blue-200 dark:hover:bg-blue-300 dark:text-blue-800 mb-2"
                  href="/blog/tag/alpine-js/"
                >
                  # {k}
                </a>
                ))}
              </div>
              {doc.published && <p className="text-sm text-gray-400">Published {doc.age} ago</p> }
            </div>
            <Link href={'/article/' + doc.slug}>
              <h2 className="font-bold text-black text-2xl mb-3 dark:text-white hover:underline">{doc.title}</h2>
            </Link>
            {doc.description && <p className="text-gray-500">{doc.description}</p>}
            <a href="" className="flex flex-row space-x-3 text-blue-500 self-end right-0 absolute text-sm hover:underline "><span>Read more </span><MoveRight /></a>
          </article>
        ))}
      </div>
      <div className="w-1/4">
        <div className="p-6 pb-4 mt-6 mb-6 font-medium text-gray-500 bg-white border border-gray-200 rounded-lg dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400">
          <h4 className="mb-4 font-bold text-gray-900 uppercase dark:text-white">
            Recommended topics
          </h4>
          <div className="flex flex-wrap">
            <a
              className="bg-blue-100 text-blue-800 text-sm font-medium mr-2 px-2.5 py-0.5 rounded dark:bg-blue-200 hover:bg-blue-200 dark:hover:bg-blue-300 dark:text-blue-800 mb-2"
              href="/blog/tag/alpine-js/"
            >
              #Alpine.js
            </a>
            <a
              className="bg-blue-100 text-blue-800 text-sm font-medium mr-2 px-2.5 py-0.5 rounded dark:bg-blue-200 hover:bg-blue-200 dark:hover:bg-blue-300 dark:text-blue-800 mb-2"
              href="/blog/tag/angular/"
            >
              #Angular
            </a>
            <a
              className="bg-blue-100 text-blue-800 text-sm font-medium mr-2 px-2.5 py-0.5 rounded dark:bg-blue-200 hover:bg-blue-200 dark:hover:bg-blue-300 dark:text-blue-800 mb-2"
              href="/blog/tag/flowbite/"
            >
              #Flowbite
            </a>
            <a
              className="bg-blue-100 text-blue-800 text-sm font-medium mr-2 px-2.5 py-0.5 rounded dark:bg-blue-200 hover:bg-blue-200 dark:hover:bg-blue-300 dark:text-blue-800 mb-2"
              href="/blog/tag/laravel/"
            >
              #Laravel
            </a>
            <a
              className="bg-blue-100 text-blue-800 text-sm font-medium mr-2 px-2.5 py-0.5 rounded dark:bg-blue-200 hover:bg-blue-200 dark:hover:bg-blue-300 dark:text-blue-800 mb-2"
              href="/blog/tag/next-js/"
            >
              #Next.js
            </a>
            <a
              className="bg-blue-100 text-blue-800 text-sm font-medium mr-2 px-2.5 py-0.5 rounded dark:bg-blue-200 hover:bg-blue-200 dark:hover:bg-blue-300 dark:text-blue-800 mb-2"
              href="/blog/tag/tailwind-css/"
            >
              #Tailwind CSS
            </a>
          </div>
        </div>
        <div className="p-6 pb-4 mt-6 mb-6 font-medium text-gray-500 bg-white border border-gray-200 rounded-lg dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400">
          <h4 className="mb-4 font-bold text-gray-900 uppercase dark:text-white">
            Latest Articles
          </h4>
          <div className="flex flex-col">
            <div className=" border-b pb-2 mb-2">
              <h4>Article Title</h4>
              <div>3 days ago</div>
            </div>
            <div className=" border-b pb-2 mb-2">
              <h4>Article Title</h4>
              <div>5 day ago</div>
            </div>
            <div className=" border-b last:border-none">
              <h4>Article Title</h4>
              <div>10 days ago</div>
            </div>
          </div>
        </div>
      </div>
    </main>
  );
}
